### ISSUE TITLE
增加功能：下载收藏夹内容

### ISSUE THREAD

**Issue by oarinv** [niuhuan/bilirust#4]
获取用户收藏夹全部内容，根据bvid，下载收藏夹内所有视频
api 接口 ：https://api.bilibili.com/x/v3/fav/resource/ids

**url参数：**

| 参数名   | 类型 | 内容                     | 必要性 | 备注                        |
| -------- | ---- | ------------------------ | ------ | --------------------------- |
| media_id | num  | 目标收藏夹mlid（完整id） | 必要   |                             |
| platform | str  | 平台标识                 | 非必要 | 可为web（影响内容列表类型） |

**json回复：**

根对象：

| 字段    | 类型                            | 内容       | 备注                                                |
| ------- | ------------------------------- | ---------- | --------------------------------------------------- |
| code    | num                             | 返回值     | 0：成功<br />-400：请求错误<br />-403：访问权限不足 |
| message | str                             | 错误信息   | 默认为0                                             |
| data    | 有效时：array<br />无效或：null | 内容id列表 |                                                     |

`data`中的`medias`数组：

| 项   | 类型 | 内容            | 备注 |
| ---- | ---- | --------------- | ---- |
| 0    | obj  | 收藏内容id1     |      |
| n    | obj  | 收藏内容id(n+1) |      |
| ...  | obj  | ...             |      |

`medias`数组中的对象：

| 字段  | 类型 | 内容         | 备注                                                         |
| ----- | ---- | ------------ | ------------------------------------------------------------ |
| id    | num  | 内容id       | 视频稿件：视频稿件avid<br />音频：音频auid<br />视频合集：视频合集id |
| type  | num  | 内容类型     | 2：视频稿件<br />12：音频<br />21：视频合集                  |
| bv_id | str  | 视频稿件bvid |                                                              |
| bvid  | str  | 视频稿件bvid |

**Comment by niuhuan** [comment]
参数是哪里来的？或者是从页面获取？

**Comment by niuhuan** [comment]
我打开我的收藏夹是这样的

`https://space.bilibili.com/1234567/favlist?fid=56789`

然后

`https://api.bilibili.com/x/v3/fav/resource/list?media_id=56789&pn=1&ps=20&keyword=&order=mtime&type=0&tid=0&platform=web`

看起来是能爬的亚子

**Comment by oarinv** [comment]
根据url 来的 media_id=fid

**Comment by oarinv** [comment]
> 我打开我的收藏夹是这样的
> 
> `https://space.bilibili.com/1234567/favlist?fid=56789`
> 
> 然后
> 
> `https://api.bilibili.com/x/v3/fav/resource/list?media_id=56789&pn=1&ps=20&keyword=&order=mtime&type=0&tid=0&platform=web`
> 
> 看起来是能爬的亚子

https://api.bilibili.com/x/v3/fav/resource/ids?media_id=56789&keyword=&order=mtime&type=0&tid=0&platform=web
这样能显示所有视频，不用分页
